/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { RedTickets } from "./RedTickets";
export type { Rocket } from "./Rocket";
